FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABSE_URL
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/frontend ./apps/frontend

RUN bun install
RUN bun run db:generate
RUN DATABSE_URL=${DATABSE_URL} bun run build

EXPOSE 3000

CMD ["bun","run","start:web"]
